---
username: "<username>"

docker_dir: /home/{{ username }}/docker_apps
data_dir: /home/{{ username }}/data

puid: "<puid>"

pgid: "<pgid>"

ip_address: "<server_ip>"

timezone: "<timezone>"

domain: "<domain_name>"

cloudflare_email: "<cloudflare_email>"

cloudflare_api_key: "<cloudflare_api_key>"

traefik_basic_auth_hash: "<traefik_basic_auth_hash>"

jwt_secret: "<jwt_secret>"

authelia_sqlite_encryption_key: "<authelia_sqlite_encryption_key>"

google_mail: "<google_email>"

google_insecure_app_pass: "<google_insecure_app_pass>"

authelia_admin_mail: "<authelia_admin_mail>"

authelia_admin_argon2id_pass: "<authelia_admin_argon2id_pass>"

wg_password: "<wg_pass>"

codeserver_password: "<code_pass>"

packages:
  - unzip
  - wget
  - curl
  - git
  - python3
  - python3-pip

pip_packages:
  - ansible
  - github3.py
  - docker

docker_dependencies:
  - ca-certificates
  - gnupg
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# photoprism
photoprism_mysql_root_password: "<photoprism_mysql_root_password>"
photoprism_mysql_db: "photoprism"
photoprism_mysql_user: "photoprism"
photoprism_mysql_password: "<photoprism_mysql_password>"